SET SERVEROUTPUT ON

-- HR OPS AUTOMATION SUITE DDL

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_employee_docs CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;

/

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_audit_log CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;

/

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_payroll_snapshot CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;

/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE cs_transfers CASCADE CONSTRAINTS';
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;
/


BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_employee_salary CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL;
END;

/

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_employees CASCADE CONSTRAINTS'; 
EXCEPTION
    WHEN OTHERS THEN NULL; 
    END;
/

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_departments CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;

/

BEGIN 
    EXECUTE IMMEDIATE 'DROP TABLE cs_user_identity CASCADE CONSTRAINTS'; 
EXCEPTION 
    WHEN OTHERS THEN NULL; 
END;

/


-- Departments
CREATE TABLE cs_departments (
dept_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
dept_name   VARCHAR2(100) NOT NULL,
location    VARCHAR2(100),
created_at  DATE DEFAULT SYSDATE NOT NULL
);

-- Employees
CREATE TABLE cs_employees (
emp_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name  VARCHAR2(50) NOT NULL,
last_name   VARCHAR2(50) NOT NULL,
email       VARCHAR2(120) UNIQUE NOT NULL,
phone       VARCHAR2(20),
hire_date   DATE DEFAULT SYSDATE NOT NULL,
dept_id     NUMBER NOT NULL REFERENCES cs_departments(dept_id),
job_title   VARCHAR2(80) NOT NULL,
manager_id  NUMBER NULL,
status      VARCHAR2(20) DEFAULT 'ACTIVE'
CHECK (status IN ('ACTIVE','INACTIVE')),
created_by  VARCHAR2(50) DEFAULT USER,
created_at  DATE DEFAULT SYSDATE NOT NULL,
updated_at  DATE
);

-- Salary 
CREATE TABLE cs_employee_salary (
emp_id      NUMBER PRIMARY KEY
REFERENCES cs_employees(emp_id),
base_salary NUMBER(10,2) NOT NULL CHECK (base_salary >= 0),
bonus       NUMBER(10,2) DEFAULT 0 CHECK (bonus >= 0),
currency    VARCHAR2(3) DEFAULT 'INR',
updated_at  DATE DEFAULT SYSDATE NOT NULL
);

-- Transfers
CREATE TABLE cs_transfers (
transfer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
emp_id      NUMBER NOT NULL REFERENCES cs_employees(emp_id),
from_dept_id NUMBER NOT NULL,
to_dept_id   NUMBER NOT NULL,
effective_on DATE NOT NULL,
reason       VARCHAR2(200),
created_at   DATE DEFAULT SYSDATE NOT NULL
);

-- Payroll snapshot
CREATE TABLE cs_payroll_snapshot (
snap_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
snap_month  DATE NOT NULL,
emp_id      NUMBER NOT NULL REFERENCES cs_employees(emp_id),
gross_pay   NUMBER(10,2) NOT NULL,
tax_amount  NUMBER(10,2) NOT NULL,
net_pay     NUMBER(10,2) NOT NULL,
created_at  DATE DEFAULT SYSDATE NOT NULL,
CONSTRAINT uq_snap UNIQUE (snap_month, emp_id)
);

-- Audit Log
CREATE TABLE cs_audit_log (
audit_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
table_name  VARCHAR2(30) NOT NULL,
action_type VARCHAR2(10) NOT NULL,
pk_value    VARCHAR2(100),
changed_by  VARCHAR2(50) DEFAULT USER,
changed_at  DATE DEFAULT SYSDATE NOT NULL,
details     CLOB
);

-- Employee Documents
CREATE TABLE cs_employee_docs (
doc_id      NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
emp_id      NUMBER NOT NULL REFERENCES cs_employees(emp_id),
doc_type    VARCHAR2(30) NOT NULL,
file_name   VARCHAR2(200),
mime_type   VARCHAR2(100),
doc_content BLOB,
uploaded_at DATE DEFAULT SYSDATE NOT NULL
);


-- User Identity
CREATE TABLE cs_user_identity (
    db_username VARCHAR2(30) PRIMARY KEY,
    emp_id      NUMBER 
); 

-- Indexes 
CREATE INDEX idx_emp_dept ON cs_employees(dept_id);
CREATE INDEX idx_payroll_emp ON cs_payroll_snapshot(emp_id);
CREATE INDEX idx_transfers_emp ON cs_transfers(emp_id);


-- Roles

-- HR ADMIN
CREATE ROLE role_hr_admin;
GRANT SELECT, INSERT, UPDATE, DELETE ON cs_employee_salary TO role_hr_admin;

-- MANAGER
CREATE ROLE role_manager;
GRANT SELECT ON cs_employee_salary TO role_manager;

-- EMPLOYEE
CREATE ROLE role_employee;
GRANT SELECT ON cs_employee_salary TO role_employee;

-- HR Context
CREATE CONTEXT hr_ctx USING pkg_hr_security;


-- Users

GRANT role_hr_admin TO hr_ops;

CREATE USER manager_pep IDENTIFIED BY manager123;
GRANT role_manager TO manager_pep;
GRANT CREATE SESSION TO manager_pep;

CREATE USER employee_kevin IDENTIFIED BY employee123;
GRANT role_employee TO employee_kevin;
GRANT CREATE SESSION TO employee_kevin;

