CREATE USER hr_ops IDENTIFIED BY hr_ops
DEFAULT TABLESPACE users
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO hr_ops;
GRANT CREATE TABLE TO hr_ops;
GRANT CREATE VIEW TO hr_ops;
GRANT CREATE SEQUENCE TO hr_ops;
GRANT CREATE PROCEDURE TO hr_ops;
GRANT CREATE TRIGGER TO hr_ops;
GRANT CREATE TYPE TO hr_ops;
GRANT CREATE JOB TO hr_ops;
GRANT UNLIMITED TABLESPACE TO hr_ops;
GRANT CREATE ROLE TO HR_OPS;
GRANT CREATE ANY CONTEXT TO HR_OPS;
GRANT CREATE USER TO HR_OPS;
GRANT CREATE SESSION TO HR_OPS WITH ADMIN OPTION;
/

-- NEED TO RUN AS SYS/SYSTEM ON CONTAINER DB
GRANT EXECUTE ON DBMS_RLS TO HR_OPS;
